### ISSUE TITLE
cross compiled the lldpd 0.7.19 and it didnt make a lldpd executable

### ISSUE THREAD

**Issue by kuroroo** [vincentbernat/lldpd#150]
Hi,

i manage to cross compiled the lldpd 0.7.19 for arm but it didnt create a lldpd executable files.

i used ./configure --prefix=/home/user/build_lldpd/ --host=arm-arago-linux-gnueabi --with-privsep-user=root --with-privsep-group=root

why it didnt create the lldpd executable files?.

thanks.
kuroroo

**Comment by vincentbernat** [comment]
Dunno. What is the output of make? (the end of it)

**Comment by kuroroo** [comment]
when using "make" command the output is:

Making all in tests
make[2]: Entering directory `/home/user/lldpd-0.7.19/tests'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/home/user/lldpd-0.7.19/tests'
Making all in osx
make[2]: Entering directory `/home/user/lldpd-0.7.19/osx'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/home/user/lldpd-0.7.19/osx'
make[2]: Entering directory `/home/user/lldpd-0.7.19'
  GEN      ChangeLog
make[2]: Leaving directory `/home/user/lldpd-0.7.19'
make[1]: Leaving directory `/home/user/lldpd-0.7.19'

**Comment by vincentbernat** [comment]
Use `make install DESTDIR=$PWD/target`. You should have your executables in `target/usr/local/sbin/lldpd` and `target/usr/local/sbin/lldpcli`.

**Comment by kuroroo** [comment]
i tried it but it didnt create the executables..
that command only create a "target" directory inside lldpd-0.7.19 directory (we are using prefix in the ./configure) which is..
/home/user/lldpd-0.7.19/target/home/user/build_lldpd/sbin.. inside /sbin are lldpcli(type: shared library), lldpctl(type: shared library), lldpd(type: shared library) but not as executables its a shared library..
its the same as before..
i used --prefix=/home/user/build_lldpd in my ./configure.. the executables should be put inside /home/user/build_lldpd/sbin... but instead of executables it produce lldpcli, lldpctl, lldpd as shared library.. i'm using VM ubuntu 10.04 to cross compile the lldpd-0.7.19 for ARM.. i want to put all the installed files inside build_lldpd directory thats why i used --prefix..

thanks,
kuroroo

**Comment by kuroroo** [comment]
i tried it but it didnt create the executables.. (i checked the /usr/local/sbin)..
that command only create a "target" directory inside lldpd-0.7.19 directory which is..
/home/user/lldpd-0.7.19/target/home/user/build_lldpd/sbin.. inside /sbin are lldpcli(type: shared library), lldpctl(type: shared library), lldpd(type: shared library) but not as executables, its a shared library..
its the same as before..
i used --prefix=/home/user/build_lldpd in my ./configure.. the executables should be put inside /home/user/build_lldpd/sbin... but instead of executables it produce lldpcli, lldpctl, lldpd as shared library.. i'm using VM ubuntu 10.04 to cross compile the lldpd-0.7.19 for ARM.. i want to put all the installed files inside build_lldpd directory thats why i used --prefix..

thanks,
kuroroo

**Comment by vincentbernat** [comment]
Totally unrelated, but you should use `DESTDIR` instead of `--prefix` since `--prefix` should indicate the prefix on the installed system. Otherwise, `lldpd` won't be able to find `lldpcli` to configure itself.

The executable creation is delegated to libtool, like in any autotools project.

Maybe libtool is confused by the use of position independant executable (or your target platform doesn't support that). Try to configure with `--disable-hardening` to not use this functionality.

**Comment by kuroroo** [comment]
your a genius!

i added --disable-hardening in my ./configure and it built lldpd, lldpcli executable files inside /home/user/build_lldpd/sbin.. im using --prefix because im just compiling something for use on a single host..

btw, can you explain that --disable-hardening i want to know whats the use of that.. 

thanks man,
kuroroo

**Comment by vincentbernat** [comment]
When using `--prefix` like you do, `lldpd` will look for `lldpcli` in the specified prefix. You'll need to specify its correct location with `-L` if it's not here.

`--disable-hardening` disable various security features, notably PIE (position independant executable). Maybe you know PIC (position independant code) which is a way to make a library work without it knowing where it  will be mapped in memory: the library will be placed at a random location at runtime, making difficult for an attacker to guess where some functions are, making an exploit more difficult to use since it cannot use functions from libraries. PIE is the same thing for an executable. Instead of being loaded at a fixed position in memory, it is loaded at a random location. Internally, a PIE is in fact just a library and most dynamic linkers know how to "execute" a library (for example, try to execute libc.so, you'll get version information). However, it doesn't seem to be the case with your toolchain.
