### ISSUE TITLE
fatal: lldpd_update_localports: failed to get interface list: Invalid argument

### ISSUE THREAD

**Issue by ianmacpherson** [vincentbernat/lldpd#170]
Embedded MIPS system, which lldpd works fine with the previous software build.  My biggest issue is trying to figure out what is causing that error.  Not sure where to start.  I can say that it seems to happen about 5 mins after machine bootup.

Thanks!

**Comment by vincentbernat** [comment]
What were the working versions?

**Comment by ianmacpherson** [comment]
The version of the lldpd itself is 0.5.7.  The base image (busybox) changed slightly between the working and non-working versions.  It did previously work, but changes to SNMP and other services were made, which could have affected lldpd.  Hardware is identical.  Tried to compile 0.9.2 for debug options, but expects C99, which apparently our compiler doesn't support.

Any ideas where I can start looking?

Thanks!

**Comment by vincentbernat** [comment]
For the C99, do you get an error on configure? In this case, could you look at `config.log` to know which test fails exactly. What is your compiler? What is your libc?

For the error with 0.5.7, if you changed your libc version (a more recent of uclibc for example), you could have switched from the `getifaddrs()` function provided by lldpd by the one from your libc. Check `config.h` for `HAVE_GETIFADDRS`. If undefined, you use the one from lldpd, otherwise from your libc. If you have the output of configure from older (working) builds, the information is also present in the configure output.

**Comment by vincentbernat** [comment]
No news, closing the issue. Feel free to reopen if you get additional infos.
