### ISSUE TITLE
How does lldpd.conf file work in lldpd

### ISSUE THREAD

**Issue by bhdl** [vincentbernat/lldpd#173]
Hi Vincent,
I added to /etc/lldpd.conf file as show below:

configure lldp med policy application voice priority voice dscp 46

then run command "lldpd -M 4", I don't see LLDP message in wireshark.
If I run command lldpd -M 4 -L "", then I can see LLDP message in wireshark but no Network policy.

Do you know why?
Thank you,
Bryan

**Comment by vincentbernat** [comment]
Hi Bryan,

lldpd should be installed with `make install` (or `make install DESTDIR=somedestination` and the directory should be copied over to the target). The `-L` workaround was just a workaround. I cannot provide support for half installed versions of lldpd. As you can see in the error messages, lldpd cannot find lldpcli because it is not where it expects it.
