### ISSUE TITLE
is it possible to use LLDP to configure an IP address neighbors

### ISSUE THREAD

**Issue by Robinieu** [vincentbernat/lldpd#200]
i want to define a paket LLDP ti configure an IP address for neighbors connected,

is that possible ?

**Comment by athreyaDell** [comment]
I am not sure this is the right answer but I can suggest. You could use custom TLVs to send the IP address you want to assign. You could use this IP on the neighbor side to be configured. Ofcourse LLDP doesn't have a default api or function to do this because its not the job of lldp. Also the lldp packets may go out of all ports things like that..just a suggestion..hope this helps

**Comment by vincentbernat** [comment]
Not possible and not really in scope.

**Comment by Robinieu** [comment]
thanks atheryaDell for your reply .
i had that tested but no chance ...

**Comment by Robinieu** [comment]
tks vincentbernat for your apply.
i know that lldp is not developed for that , could you please explain why is that not posiible ?

**Comment by vincentbernat** [comment]
Everything is possible if you  put much effort in it. You could encode the IP into a custom TLV and then parse it back on the other end and configure it. But the tool you are looking for is DHCP/BOOTP/RARP, not LLDP.

**Comment by Robinieu** [comment]
tks for your apply ,
could you please give me tips on how i can encoding a custom TLV ?

**Comment by athreyaDell** [comment]
I intended to tell the same thing as Vincent, encode into custom TLV and then parse it back but LLDP is not the right thing you are looking for.

you could encode the ip into a custom tlv by using the commands you would use in case of lldpcli. These commands go into the /etc/lldpd.conf file.

For e.g. 
/etc/lldpd.conf  file contents:
configure lldp custom-tlv add oui 01,02,A1 subtype 03 oui-info 65,63,2d,32,2d,64
