### ISSUE TITLE
Instructions to build

### ISSUE THREAD

**Issue by dennypage** [vincentbernat/lldpd#268]
README.md indicates that the instructions to build are:

    ./configure
    make

however, there is no configure file included in the 0.9.9 distribution. As distributed, one must run autogen.sh to create the configure file first:

    ./autogen.sh
    ./configure
    make

Is it intended that that is no configure file in the distribution?

**Comment by vincentbernat** [comment]
People are expected to get tarballs from the [website](http://vincentbernat.github.io/lldpd/). They contain the `configure` script. People using git checkout are expected to know they should use `./autogen.sh` before that. But this was in a time where everybody was used to handle that. Maybe the instructions can now be updated. In the past, it was also believed end-users shouldn't run `./autogen.sh` since the output was dependent of its version. This is not really true today.

**Comment by dennypage** [comment]
Yea, I pulled the tarball from GitHub releases rather than from the site. My bad.
